// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Display',
       items: [
        'Display/3.5″ RPi LCD CTP',
        'Display/3.5″ RPi LCD RTP',
        'Display/4.3inch-DSI-Touchscreen',
        'Display/5inch-DSI-Touchscreen',
        'Display/7inch-DSI-TOUCH-A',
        'Display/7inch-DSI-Touchscreen',
        'Display/7inch-HD-Touchscreen',
        'Display/7inch-HD-Touchscreen-V4',
        'Display/8inch-DSI-TOUCH-A',
        'Display/10.1inch-HD-Touchscreen',
        'Display/14inch-Portable-Monitor',
        'Display/15.6inch-Portable-Monitor',
        'Display/18.5″ 4K Portable Monitor',
        'Display/18.5inch-Portable-Monitor',
        'Display/18.5inch-Touch-Monitor',
        'Display/21.5″ Portable Monitor',
        'Display/24.5″ 2K Portable Monitor',
      ],
    },
    {
      type: "link",
      label: "Rockchip RV1106",
      href: "/docs/Luckfox-Pico-86-Panel",
    },
    {
      type: "link",
      label: "Rockchip",
      href: "/docs/Luckfox-Pico-86-Panel",
    }
  ],
  aSidebar: [{type: 'autogenerated', dirName: 'Luckfox Pico RV1106/Luckfox-Pico-86-Panel'},],
  bSidebar: [{type: 'autogenerated', dirName: 'Luckfox Pico RV1106/Luckfox-Pico-86-Panel'},],
  
};

export default sidebars;
